spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camshopmall?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: hejun1519201822
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MySQL5Dialect
#     更新或者创建数据表结构
      ddl-auto: update
#    控制台显示SQL
    show-sql: true
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 2967627664@qq.com #发送邮件的邮箱地址
    password:  buanbygtrykidcia #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 2967627664@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8 
 